
name: "dbt_duckdb_preppin_data"
version: "1.0.0"

profile: "dbt_duckdb_preppin_data"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  dbt_duckdb_preppin_data:
    0__Input:
      +schema: input
      +tags:
        - input
    1__Output:
      +schema: output
      +tags:
        - output
